name: fluttergorestapi
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_keyboard_visibility: ^6.0.0
  provider: ^6.1.2

environment:
  sdk: '>=3.7.0 <4.0.0' 

dev_dependencies:
  flutter_test:
    sdk: flutter